#ifndef CONSTANTS_H
#define CONSTANTS_H

// constants
#define MAIN_MEMORY_PAGES 100
#define PAGE_SIZE_MB 1
#define MAX_PROCESS_SIZE_MB 31
#define MIN_PROCESS_SIZE_MB 5
#define MAX_SERVICE_DURATION 5
#define MIN_SERVICE_DURATION 1
#define TOTAL_PROCESSES 800
#define RUNS_PER_ALGORITHM 5
#define SIMULATION_TIME_SEC 60

#endif // cONSTANTS_H
